Feature/project graph
ccims/gropius-backend pull request #65
Opened 2023-11-12 17:06 UTC by nk-coding

Adds project graph capabilities
- styling for relations / components / interfaces
- issue aggregation
- improved filtering options for RelationPartners

2023-11-12 19:53 UTC, spethso requested changes
Minor change request for grammar mistake in documentation

2023-11-12 20:34 UTC, nk-coding commented on core/src/main/kotlin/gropius/model/template/style/MarkerType.kt
Currently this list represents what the frontend supports.
But I can add circles on both ends

2023-11-12 20:36 UTC, nk-coding commented on api-common/src/main/kotlin/gropius/graphql/GraphQLConfiguration.kt
> +     * Filter for [RelationPartner]s which part of the graph of a specific [Project]
fixed with 38f3d4a2ef272ec66d4af79a34cc8f1b62ceae58

2023-11-13 08:18 UTC, spethso approved these changes

2023-11-13 09:35 UTC, merged